### ISSUE TITLE
Github Action Failing even tho the Tests passed

### ISSUE THREAD

**Issue by Urento** [mvdan/github-actions-golang#23]
When I run this Github Action:
```
on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Redis
        # You may pin to the exact commit or the version.
        # uses: zhulik/redis-action@765216a54a1114f109ce90a1de4775080be16ea5
        uses: zhulik/redis-action@1.1.0
      - name: Setup PostgreSQL
        # You may pin to the exact commit or the version.
        # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # POSTGRES_DB - name for the default database that is created
          postgresql db: shoppinglistboom
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: shoppinglist
          # POSTGRES_PASSWORD - superuser password
          postgresql password: postgres
      - name: Build
        working-directory: ./backend
        run: go build ./...
      - name: Test
        working-directory: ./backend
        run: go test ./...
        env:
          DB_HOST: localhost
          DB_USER: shoppinglist
          DB_DATABASE: shoppinglistboom
          DB_PASSWORD: postgres
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          DATABASE_DSN: host=localhost user=shoppinglist password=postgres dbname=shoppinglistboom sslmode=disable
          TESTING: true
```
it fails every time due to the Tests. But when I look at the logs it says that the Tests passed.
![grafik](https://user-images.githubusercontent.com/58522564/125161528-27d26f80-e183-11eb-9540-d688b9134244.png)

It gives me the exit code 2 but I dont know what to do with that.
